version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=destr0
      - POSTGRES_PASSWORD=12345m
      - POSTGRES_DB=urlshort
    ports:
      - 5432:5432
    volumes :
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql

  backend:
    container_name: urlshort-dev
    image: urlshort-dev
    build:
      context: .
      target: development
    volumes:
      - .:/urlshort
    environment:
      - DATABASE=postgres://destr0:12345m@db:5432/urlshort?sslmode=disable
    depends_on:
      - db
    ports:
      - 8080:8080